### ISSUE TITLE
rename the project so it's findable

### ISSUE THREAD

**Issue by sean808080** [RafaelGB/Obsidian-ZettelFlow#31]
this project is called obsidian-zettlelflow which makes it impossible to find because the correct spelling is ZETTEL so suggest renaming the project to obsidian-zettelflow or just zettelflow for simplicity and to help people searching for zettelkasten plugins to find this one.

Good luck.

**Comment by RafaelGB** [comment]
thanks for your suggestion, I will check those kind of typos

**Comment by RafaelGB** [comment]
Changed!

**Comment by sean808080** [comment]
Thanks.  You probably want to change the mis-spelling everywhere since it's still showing up in the docs.  👍🏾

**Comment by RafaelGB** [comment]
Also was changed inside the code =P thanks again
