### ISSUE TITLE
Provide installation instructions 

### ISSUE THREAD

**Issue by sean808080** [RafaelGB/Obsidian-ZettelFlow#34]
I didn't think I was a newbie but I am not able to install this plug-in.  This plug-in does not appear in the community plug-ins section in the app so I attempted to install it by dropping the source folder into the hidden plugins directory.  After doing this, I still was not able to find the plug anywhere in the plug ins listing.

If there is some step I am missing, perhaps an install guide would be helpful.  I read the readme and it did not offer any guidance.

**Comment by RafaelGB** [comment]
Hello!  Currently its a beta. So you can only install it with [BRAT](https://github.com/TfTHacker/obsidian42-brat)

**Comment by sean808080** [comment]
doh.  I have not used BRAT but it might help the next noob save some time and frustration by including that in the documentation.  If it's there I missed it. :-)

**Comment by RafaelGB** [comment]
I will add a warning of BETA with a link to BRAT then. Hope Obsidian approves my petition of publish the plugin soon

**Comment by sean808080** [comment]
sounds good.  Hope it's approved.  So I installed BRAT and enabled this plug in but it's not very obvious where to start.   Perhaps a youtube video going over how to use the plug in would be useful because using a canvas to drive the creation of notes is not something you see every day.  I'm eager to learn how to use it....

**Comment by RafaelGB** [comment]
once you enable the plugin, you have a mini tutorial the first time you click on the plugin ribbon icon

I will work on a web with all the documentation

**Comment by RafaelGB** [comment]
The plugin was already published !
The brat instructions will not be necessary

**Comment by sean808080** [comment]
Congratulations!
