### ISSUE TITLE
Bug: Cannot enable plugin

### ISSUE THREAD

**Issue by jtvilm** [RafaelGB/Obsidian-ZettelFlow#49]
Hi RafaeGB,

after I successfully installed the plugin in Obsidian, *enabling* it fails with the error message "Failed to load plugin Zettelflow".

Looking into the console log the following message appears:

![grafik](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/2485974/a90373ac-4405-43ad-a2dc-478d2601843a)

Any ideas how to resolve this?

Best,
jtvilm

**Comment by RichardUUU** [comment]
Same problem here.

**Comment by jtvilm** [comment]
> hi @jtvilm , what operative system are you using?
> 
> I will try to reproduce it to find the cause.

Windows 11 Pro 22H2 with all available updates.

**Comment by RafaelGB** [comment]
maybe its an incompatibility with another plugin. Could you try to disable the other ones?

I test the install of v1.3.0 with MacOS and Windows 11 and works correctly on multiple devices

**Comment by jtvilm** [comment]
Sure, will try, just give me some days to get there ... I have quite some plugins installed.

**Comment by RafaelGB** [comment]
thanks, I really appreciate it. Whirl I have planned. 1.3.1 this week with some improvements and I will try to test it with another devices

**Comment by RafaelGB** [comment]
I found the problem:
On mobile and with the old Obsidian install setup for desktops, codemirror v5 is used and with the script actions I am using the v6

```json
"@codemirror/lang-javascript": "6.2.1",
```

Until Obsidian supports on mobile the v6 we can rollback the js linter support or find an alternative

**Comment by RafaelGB** [comment]
confirm that is fixed with 1.3.3 and I will close the issue

**Comment by jtvilm** [comment]
Hi RafaelGB,

thanks for the efforts! I can confirm that it can be enabled correctly :)

Cheers,
jtvilm

**Comment by RafaelGB** [comment]
thanks for confirming!

We lost the feature of highlighting the code editor with js capacities, but once codemirror 6 arrives to mobile we can install the dependency again

**Comment by jtvilm** [comment]
I am just getting started with this plugin, so I am sure that I can live without the code highlight for now ;) Thanks again!
