### ISSUE TITLE
Doesn't seem to want to create actions or interactions?

### ISSUE THREAD

**Issue by gtaylor90** [RafaelGB/Obsidian-ZettelFlow#50]
Not sure how to describe this one other than it seems like it's just not working. I'll include some screenshots here to help explain but I've tried uninstalling the plugin and reinstalling and even making a fresh vault and starting fresh. Maybe I'm missing something, hard to tell since I previously had the issue where the plug-in wouldn't enable, so haven't been able to set up a successful workflow yet. 

Canvas was set and selected in settings. So far just two things on it, "Fleeting note" and what should be a prompt action. 
![image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/17018179/72f1550c-05ea-403c-aef9-8b70e06a301d)

When I go to edit the step for the Root fleeting note, it looks pretty sparse but that seems to be in-line with what normal root notes look like. 
![image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/17018179/24e83184-90fe-43cc-871a-9d274d653361)

However when we go to look at the action note it too looks sparse. 
![image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/17018179/1ae6b899-bd90-4833-8638-48dcd7ad6851)

When trying to add an action using the [+] button, I get nothing. Swapping to another action types produce the same effect. 

The action names themselves look like maybe they're not rendering correctly as well, which is what I believe is maybe indicative of what the root cause of this issue is, but wouldn't know enough about the whole application to know how to fix it, but it's the one thing I can definitively say is different from what I've seen in other's screenshots.
![image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/17018179/de39e2f6-057a-434c-899c-f0403d2541d3)
>usually they're labeled just "Prompt" or "Backlink" not "promptPrompt" etc. 

I had some other plug-ins installed but have disabled/deleted them and just have ZettelFlow active, so don't believe that's the issue here. 

If I go to create a note, it does recognize the root note, but won't let me progress through the dialogue modal.
![image](https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/17018179/45dc9760-8072-4f44-bde1-675e7adb59b9)
>not sure what the red note icon is but seems different as well. 

Hopefully this is resolvable, as it seems like a very cool system/plugin!

**Comment by RafaelGB** [comment]
hello @gtaylor90 it was a but of v1.3.3

It's resolved with 1.4.0. Today was a very productive day with multiple versions to achieve the 1.4.0, let me know if it fixed!

**Comment by gtaylor90** [comment]
Yup! seems to be working now, thanks!
