### ISSUE TITLE
”calendar action_frontmatter“ create frontmatter property value(field value) do not match builder UI,then i cant use this property value in the obsidian project plugin

### ISSUE THREAD

**Issue by farrellyuan** [RafaelGB/Obsidian-ZettelFlow#63]
builder UI when using calendar action_frontmatter is
<img width="653" alt="image" src="https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/104613481/6410a82e-677e-46a4-a036-e44101088181">

the wrong frontmatter property value(field value) in the created new note is 
<img width="545" alt="image" src="https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/104613481/6e9ac185-5542-4c63-8971-db42e90e758b">

the right frontmatter property value(field value) in the created new note is supposed to be
<img width="405" alt="image" src="https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/104613481/2c001fb8-f09d-44d1-8cd1-8b53599aeb7d">

So how can i can get "date value format= YYYY-MM-DD", what should i do?

Thanks for ur help.

**Comment by RafaelGB** [comment]
Hello @farrellyuan , Sure! we can check the Obsidian daily format setting and apply it when its a date.
I think the local date-time option should maintain this format, It will be apply just for "normal" dates.

How would you see that solution?
thanks for your feedback!

**Comment by RafaelGB** [comment]
<img width="966" alt="Screenshot 2024-02-18 at 21 49 41" src="https://github.com/RafaelGB/Obsidian-ZettelFlow/assets/11924043/df8e584e-aef5-48f4-a09a-27f6389ee56a">

Solved with a new setting

**Comment by farrellyuan** [comment]
> <img alt="Screenshot 2024-02-18 at 21 49 41" width="966" src="https://private-user-images.githubusercontent.com/11924043/305745627-df8e584e-aef5-48f4-a09a-27f6389ee56a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzOTA2NTgsIm5iZiI6MTcwODM5MDM1OCwicGF0aCI6Ii8xMTkyNDA0My8zMDU3NDU2MjctZGY4ZTU4NGUtYWVmNS00OGY0LWEwOWEtMjdmNjM4OWVlNTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDAwNTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOWVjOWJiZDc4NmE1MTA4NmJmYjdlYWE4Y2UzMjBlYjdmYmMyNzkwYWZlYmM0Njc5MGZiYTMxZmY5ZGFjNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e1TKdh9qovzInoVVu_VPzf4hHuw4S5fbrd-a5nYwkQ4">
> Solved with a new setting

This sl the problem,thank you
